CREATE TABLE books (
    book_id INTEGER PRIMARY KEY generated by default AS IDENTITY,
    title VARCHAR(255),
    publication_year INTEGER,
    in_stock BOOLEAN DEFAULT true,
    author_id INTEGER REFERENCES authors(author_id) NOT NULL
);